### ISSUE TITLE
single datapoint plotted a year in the past

### ISSUE THREAD

**Issue by dtron** [mtoebes/MFP-chart-overhaul#1]
<img width="742" alt="screen shot 2015-09-27 at 18 24 15" src="https://cloud.githubusercontent.com/assets/423720/10129136/b7572998-656f-11e5-902b-17284043faf0.png">

On hover, weird point shows as Jan 1, 2014. The points immediately to the left and right of the departure are Dec 19, 2015 and Jan 8, 2015; the . Looking at my "check in" tab on MFP, I do have a record for Jan 1, 2015 (the same weight it shows on hover) but no record for Jan 1, 2014.

I'm have no idea what info you need to figure out what's causing this bug, but let me know if you need anything from me.

**Comment by mtoebes** [comment]
Sorry for the late reply! I did not see this. I bet there is an issue in my year number calculation when it involves the first day of the year. Give me a day or two to look into it.

**Comment by dtron** [comment]
Hey, not trying to bug you about this, since it doesn't really bother me that much, but I wanted to post another update -- It's doing the same thing this year change now, as well -- jumps back to Jan 1, 2015. 

![image](https://cloud.githubusercontent.com/assets/423720/12220879/098365cc-b739-11e5-95bd-01d9339f69c8.png)

**Comment by mtoebes** [comment]
I will glance at it tonight but otherwise I will tackle it on Sunday. I am very sorry for not fix this for you when you first asked.

**Comment by dtron** [comment]
Really, there's no hurry. Just wanted to give you another data point, in
the hopes it would help you figure out what's going on with it. : )

**Comment by mtoebes** [comment]
ok, fixed. I'll probably go back later to clean up the logic but I'm tired :(. You should be able to get version 0.6 on the store soon, the store says it may take up to an hour to become available. logic for decrementing year was off by 1 iteration (MFP does not include the year on their data points). happy tracking.
